# https://www.appveyor.com/docs/appveyor-yml/

# Test against these versions of Node.js.
environment:
  MOCHA_REPORTER: "mocha-appveyor-reporter"
  matrix:
    - nodejs_version: "4"
    - nodejs_version: "6"

branches:
  only:
    - master
    - beta
    - release

# Install scripts. (runs after repo cloning)
install:
  - git rev-parse HEAD
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Install-Product node $env:nodejs_version
  # Install PhantomJS
  - npm install phantomjs-prebuilt
  - npm install mocha-appveyor-reporter
  # Typical npm stuff.
  - npm version
  - npm install

cache:
  - '%APPDATA%\npm-cache -> package.json'
  - '%APPDATA%\Roaming\bower'


# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - npm version
  - cmd: npm run test-all

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
