# DEPRECATION:
#
# Support for generating a Travis CI config file is deprecated.
# You can keep using Travis CI, or you could also consider switching to GitHub Actions instead.
#
# Feel free to remove this comment block if you want to continue using Travis CI.
#
# ID     travis-ci-support
# UNTIL  6.0.0
# URL    https://deprecations.emberjs.com/id/travis-ci-support

---
language: node_js
node_js:
  # we recommend testing addons with the same minimum supported node version as Ember CLI
  # so that your addon works for all apps
  - "18"

dist: xenial

addons:
  chrome: stable
<% if (yarn) { %>
cache:
  yarn: true
<% } else { %>
cache:
  directories:
    - $HOME/.npm
<% } %>
env:
  global:
    # See https://github.com/ember-cli/ember-cli/blob/master/docs/build-concurrency.md for details.
    - JOBS=1

branches:
  only:
    - master
    # npm version tags
    - /^v\d+\.\d+\.\d+/

jobs:
  fast_finish: false
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs linting and tests with current locked deps
    - stage: "Tests"
      name: "Tests"
      script:
        - <% if (yarn) { %>yarn<% } else { %>npm run<% } %> lint
        - <% if (yarn) { %>yarn<% } else { %>npm run<% } %> test:ember

    - stage: "Additional Tests"
      name: "Floating Dependencies"
      install:<% if (yarn) { %>
        - yarn install --no-lockfile --non-interactive<% } else { %>
        - npm install --no-package-lock<% } %>
      script:
        - <% if (yarn) { %>yarn<% } else { %>npm run<% } %> test:ember

    # we recommend new addons test the current and previous LTS
    # as well as latest stable release (bonus points to beta/canary)
    - env: EMBER_TRY_SCENARIO=ember-lts-4.12
    - env: EMBER_TRY_SCENARIO=ember-lts-5.4
    - env: EMBER_TRY_SCENARIO=ember-release
    - env: EMBER_TRY_SCENARIO=ember-beta
    - env: EMBER_TRY_SCENARIO=ember-canary
    - env: EMBER_TRY_SCENARIO=embroider-safe
    - env: EMBER_TRY_SCENARIO=embroider-optimized
<% if (yarn) { %>
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
<% } %>
script:
  - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO
